### ISSUE TITLE
Be able to persist metadata into a database rather than on the filesystem itself

### ISSUE THREAD

**Issue by avaitla** [dolthub/dolt-workbench#118]
<img width="902" alt="Screen Shot 2024-02-05 at 12 46 37 PM" src="https://github.com/dolthub/dolt-workbench/assets/841497/8de0ef92-84ac-4b87-a070-ee60a23865d7">

We run a lot of apps in a stateless system (that can restart processes) and doesn't allow mount points. Is there anyway this tool can store its metadata into an external database (like mysql rds or dolt itself)?

Here is how metabase works, It can be provided the database credentials via environment variable which would be ideal:

https://www.metabase.com/docs/latest/installation-and-operation/configuring-application-database#mysql-or-mariadb

**Comment by tbantle22** [comment]
This is supported in v0.2.4 and I updated the [README](https://github.com/dolthub/dolt-workbench?tab=readme-ov-file#saving-connection-information-between-runs) with instructions. Let me know if that works for you!

**Comment by avaitla** [comment]
Wow that was fast!

**Comment by timsehn** [comment]
> Wow that was fast!

This is our calling card. Keep the issues flowing!
