### ISSUE TITLE
Specify the GraphQL server address from the frontend itself

### ISSUE THREAD

**Issue by avaitla** [dolthub/dolt-workbench#121]
When running this docker image locally things work fine. However in our hosting setup we run into the following error:

<img width="1225" alt="Screen Shot 2024-02-07 at 6 10 12 PM" src="https://github.com/dolthub/dolt-workbench/assets/841497/fd8d5ae1-9b8c-423e-88dd-bef659cc3528">

We have to run two processes, one for the HTTP web server and one for the GraphQL Server. How do we tell the HTTP process the precise GraphQL address to route its requests to?

Could we make both the WebUI and graphql server listen on the same port and route to the same location (https://host:port)?

**Comment by tbantle22** [comment]
I will look into this tomorrow

**Comment by tbantle22** [comment]
Hi @avaitla, would the ability to set an environment variable for the GraphQL address be an okay enough workaround for now? I can get that out today. Otherwise there are more involved solutions like building a reverse proxy but that will take longer

**Comment by avaitla** [comment]
Yeah that works.

**Comment by tbantle22** [comment]
Added an environment variable for this in 0.2.6 and added [these instructions](https://github.com/dolthub/dolt-workbench/pull/122/files#diff-da8fcbe728a9172b578e5d754f8e2df214c658c4321f610e63dd68bea828ab49) to the Docker Hub README

**Comment by avaitla** [comment]
works good
