### ISSUE TITLE
Error reported after configuring Doltgresql connection

### ISSUE THREAD

**Issue by luxingxiao** [dolthub/dolt-workbench#143]
Use the master branch to deploy through code, and after configuring the Postgres connection information, the following error is reported:
Cannot read properties of undefined (reading 'current_schema')

**Comment by tbantle22** [comment]
Hi @luxingxiao, thanks for reporting this issue. Can you give me more information about your database? Are you using a normal Postgres database or a Doltgres database (with version control?) And does your database already have schema or is it empty?

**Comment by luxingxiao** [comment]
> Hi @luxingxiao, thanks for reporting this issue. Can you give me more information about your database? Are you using a normal Postgres database or a Doltgres database (with version control?) And does your database already have schema or is it empty?

Hi @tbantle22 ,  thanks for your reply。I am using a Doltgres database (with version control). My database schema is empty.

**Comment by tbantle22** [comment]
Ah okay, Doltgres is currently in development and is still missing some
features that will allow it to work with this workbench. We are actively
working on it and as soon as it’s ready I’ll let you know!

**Comment by luxingxiao** [comment]
@tbantle22 Thank you very much for your reply. The Dolt project is great and I will continue to pay attention.

**Comment by tbantle22** [comment]
If you're okay with MySQL the workbench does work with MySQL-flavored Dolt. But if not I will keep you updated on Doltgres support
