### ISSUE TITLE
Setup a new connection error, main branch issue and secure connection problem

### ISSUE THREAD

**Issue by Trojanku** [dolthub/dolt-workbench#162]
Hello dolt-workbench developers.

I've been using dolt-workbench for some time and it's great. However, I have couple of small issues found and would like to share them with you.

My dolt-workbench version is docker image: dolthub/dolt-workbench:0.2.7. 
I use it with dolthub/dolt-sql-server:1.35.7.

1. Setup new connection fails but connection created.

During setup of a new connection to database (dolt sql server in my case), despite error occurs (for example 'getaddrinfo ENOTFOUND'), connection is created and the connection name is registered so I cannot use it when I retry to create same connection. It ends with error 'name already exists'. It seems more reasonable to not create connection when a creation request fails.

2. Staying on 'main' when trying to see commits for different branch.

Starting from "Database" tab, I switch a branch to the different one and then when I go to "Commit Log" tab, it switches back automatically to main branch. I would like to keep the chosen branch when moving through tabs. 

3. "Server does not support secure connection" when in "Spreadsheet Editor" mode.

When I want to update a table using "Spreadsheet Editor", it errors with "Server does not support secure connection" even thought, I've set the connection "Use SSL" unchecked during connection initialization.

Happy to provide more details if necessary.

**Comment by tbantle22** [comment]
Hi @Trojanku, glad to hear you're enjoying the workbench! I'll look into these issues today

**Comment by tbantle22** [comment]
Just released [0.2.8](https://github.com/dolthub/dolt-workbench/releases/tag/v0.2.8) with these fixes. Let me know if you come across anything else!
