### ISSUE TITLE
Passthrough the Author for Commits

### ISSUE THREAD

**Issue by avaitla** [dolthub/dolt-workbench#167]
Currently HostedDolt allows us to use the authors email on commits as follows:
<img width="368" alt="Screen Shot 2024-04-17 at 10 33 28 AM" src="https://github.com/dolthub/dolt-workbench/assets/841497/ca381612-2eb5-4388-b0db-9682a6e46e0f">

However there is no way to specify the committer in dolt workbench currently:
![Screen Shot 2024-04-17 at 10 34 27 AM](https://github.com/dolthub/dolt-workbench/assets/841497/4a0dd7a0-cb5f-463f-897f-697560b489d1)

This then logs a user without a clear identifier. How can we pass through a header indicating the user making the commit itself, for instance we have a reverse proxy like nginx or oauth2proxy in front that can feed in X-Forwarded-Email which we should use in our commits (https://oauth2-proxy.github.io/oauth2-proxy/configuration/overview#config-file)

<img width="773" alt="Screen Shot 2024-04-17 at 10 45 36 AM" src="https://github.com/dolthub/dolt-workbench/assets/841497/5c6528ff-35cf-4a7b-b913-e3fef7bd7a2e">

**Comment by tbantle22** [comment]
Hi @avaitla, thanks for the feature request. I can quickly add a workaround today where you can manually enter a user/email when you start a connection or want to commit and have it saved in the store. Will look into how we can make it work with a header but that may take a little longer

**Comment by avaitla** [comment]
For enterprise use cases we don't want anyone overriding this or disabling it, which is why the reverse proxy pass through header is ideal

**Comment by tbantle22** [comment]
Makes sense. I'll start looking into this today and keep you updated

**Comment by tbantle22** [comment]
I just released 0.2.10 with this change. I have an example nginx configuration [here](https://github.com/dolthub/dolt-workbench/tree/main/docker/examples/nginx-reverse-proxy) that passes through the user headers and if successful you will see this checkbox enabled in the commit modal (you'll be able to use it when creating releases and merging pull requests). 
<img width="527" alt="Screenshot 2024-04-23 at 10 15 10 AM" src="https://github.com/dolthub/dolt-workbench/assets/29443194/1ab560ab-1795-4f71-b0f0-b5cfc93bae9e">

Let me know when you have a chance to try it out and if you have any feedback!
