### ISSUE TITLE
the dolt-workbench can not be used in windows?

### ISSUE THREAD

**Issue by berisfu** [dolthub/dolt-workbench#264]

**Comment by timsehn** [comment]
The Docker version should work on Windows with any browser

**Comment by liuliu-dev** [comment]
Hi @berisfu , I've just added the Windows version of the Dolt Workbench app (x64). You can download it here: [Dolt Workbench for Windows](https://github.com/dolthub/dolt-workbench/releases/download/v0.2.13/dolt-workbench-win-x64.exe).
