### ISSUE TITLE
"Wizard" for defining a remote

### ISSUE THREAD

**Issue by timsehn** [dolthub/dolt-workbench#318]
When creating a remote, right now we have two text entry boxes with name and URL.

The URL is particular is kind of hard to "discover". I think there should be more of a "point and click" interface where you select DoltHub, DoltLab or other and then guides you through a step-by-step workflow to assemble the URL.

Steps would be:

1. Radio button with DoltHub, DoltLab, Other
2. Choices
  a. if DoltHub, URL is dolthub.com/, 
  b. If DoltLab, prompt to enter DoltLab URL, test to make sure it is a valid remote 
  c. If Other, have a raw text entry box for remote
3. Choose org and database name, autofill with current database name

We could also potentially add Hosted Dolt.

**Comment by liuliu-dev** [comment]
completed
